### ISSUE TITLE
problem with STARZ

### ISSUE THREAD

**Issue by skialpine** [mludowise/AppleTV-XFinity-Activation#4]
I am seeing a 4 character activation code from STARZ, the tool does not seem to accept 4 characters.

Thanks for the great service!

**Comment by mludowise** [comment]
Good catch! The problem should be fixed now.

I don't have a STARZ subscription myself, so I can't test this. Can you please let me know if it's working for you now?

**Comment by skialpine** [comment]
Better but still now working.  

		
		

		
	





On Sat, Sep 23, 2017 at 3:30 PM -0600, "Mel Ludowise" <notifications@github..com> wrote:












Good catch! The problem should be fixed now.


I don't have a STARZ subscription myself, so I can't test this. Can you please let me know if it's working for you now?

**Comment by skialpine** [comment]
Should have said still not working. See error in attached screenshot from earlier reply. 
		
		

		
	




On Sat, Sep 23, 2017 at 4:34 PM -0600, "Jeffrey Heller" <jeffrey_heller@yahoo.com> wrote:













	
		
		
	
		Better but still now working.  

		
		

		
	





On Sat, Sep 23, 2017 at 3:30 PM -0600, "Mel Ludowise" <notifications@github..com> wrote:












Good catch! The problem should be fixed now.


I don't have a STARZ subscription myself, so I can't test this. Can you please let me know if it's working for you now?

**Comment by mludowise** [comment]
I looked into it and I think I jumped the gun on adding STARZ support because their authentication isn't as straight forward as the other networks. There is a way to authenticate STARZ with Comcast on AppleTV / Roku which is outlined in [this Reddit comment](https://www.reddit.com/r/Roku/comments/5o1g93/any_workaround_for_the_starz_appxfinity_issue_yet/), but I couldn't figure out an automated way to do it so I will be reverting my changes and pulling STARZ support.

I'm sorry that wasn't more helpful but I will let you know if I eventually figure out a solution.
